export const soups=[
    "Tavuk Suyuna Çorba",
    "Pirinçli Mercimekli Çorba",
    "Kremalı Mantar Çorbası",
    "Artan Pilavdan Pirinç Çorbası",
    "Soğuk Enginar Çorbası",
    "Bezelye Çorbası",
    "Toyga Çorbası",
    "Çeşminigar Çorbası",
    "Süt Çorbası",
    "Kabak Dolmalı Çorba",
    "Taze Soğanlı Çorba",
    "Terbiyeli Pırasa Çorbası",
    "Sebzeli Vitamin Çorba",
    "Karnabahar Çorbası",
    "Lebeniye Çorbası",
    "Sütlü Patates Çorbası",
    "Fıtı Çorbası",
    "Süleymaniye Çorbası",
    "Soğuk Çorba",
    "Ispanak Çorbası",
    "Mısır Çorbası",
    "Roka Çorbası",
    "Sebzeli Tarhana Çorbası",
    "Ezogelin Çorba",
    "Kıymalı Tarhana Çorbası",
    "Yayla Çorbası",
    "Maraş Tarhanası Çorbası",
    "Yulaf Özü Çorbası",
    "Tutmaç Çorbası",
    "Tavuk Çorbası",
    "Tarhana Çorbası",
    "Sütlü Çorba",
    "Sütlü Brokoli Çorbası",
    "Pirinç Çorbası",
    "Mantar Çorbası",
    "Labneli Soğuk Buğday Çorbası",
    "Kremalı Mantar Çorbası",
    "Kıymalı Tarhana Çorbası",
    "Kabaklı Mehir Çorbası",
    "Ispanaklı Lahana Çorbası",
    "Göceli Tarhana Çorbası",
    "Ezogelin Çorbası",
    "Et Suyuna Yayla Çorbası",
    "Et Suyuna Patates Çorbası",
    "Dana Etli Çorba",
    "Bulgur Çorbası",
    "Arpa Şehriyeli Yeşil Mercimek Çorbası",
    "Arpa Şehriyeli Ve Mercimekli Soğuk Çorba",
    "Anadolu Çorbası",
    "Alaca Çorbası",
    "Dövme Çorba",
    "Düğün Çorbası",
    "Mantı Çorbası",
    "Mercimek Çorbası",
    "Artan Pilavdan Yayla Çorbası",
    "Arpa Şehriye Çorbası",
    "Tarhana Çorbası",
    "Domatesli Tel Şehriye Çorbası",
    "Sütlü Brokoli Çorbası",
    "Domates Çorbası",
    "Yoğurt Çorbası",
    "Balkabağı Çorbası",
    "Baharatlı Kabak Çorbası",
    "Kremalı Mantar Çorbası"
]

export const meatFoods = [
    "Patatesli Soğanlı Yahni",
    "Kadınbudu Köfte",
    "Tavuk Kapama",
    "Mısır Gevrekli Tavuk Şinitzel",
    "Dalyan Köfte",
    "Beşamel Soslu Tavuk",
    "Sebzeli Köfte",
    "Köfte Mantolu Patlıcan",
    "Elbasan Tava ",
    "Saç Kavurma",
    "Kaşarlı Köfte",
    "Saray Köftesi",
    "Bohçada Et Sote",
    "Sosyetik Köfte",
    "Topalak",
    "Sebzeli Sulu Köfte",
    "Fajitas",
    "Etli Patates",
    "Izgara Köfte",
    "Köfte Yatağında Ispanak",
    "Sultanların Kebabı",
    "Kıytırık",
    "Mantarlı Biftek",
    "Sucuk Köfte",
    "Sahanda Pirzola",
    "Maklube",
    "Çin Tavuğu",
    "Çullu Köfte",
    "Soğan Soslu Dana Rosto",
    "Mısır Gevrekli Tavuk",
    "Fırında Tavuk",
    "Bulgurlu Sulu Köfte",
    "Yuvalama",
    "Darüzziyafe  Köftesi",
    "Elbasan Tava",
    "Gondol Köfte",
    "Baharatlı Kızarmış Baget",
    "Sebzeli Pane Tavuk Dolması",
    "Kadınbudu Köfte",
    "Fırında Kuzu Kol Tandır",
    "Kuzu Haşlama",
    "Tas Kebabı",
    "Fırın Torbasında  Sebzeli Pirzola",
    "Piknik Köftesi",
    "Mangal Köfte",
    "Ali Nazik",
    "Kavurma",
    "Acılı Izgara Köfte",
    "Ekşili Sulu Köfte ",
    "Ekşili Köfte ",
    "Kaburga Dolması",
    "Cevizli Tavuk Fileto",
    "Gerdaniye Kebabı",
    "Köfteli Patlıcan Kebabı",
    "Narenciye Soslu Tavuk",
    "Orman Kebabı",
    "Soğan Yahnisi (Papaz Yahnisi)",
    "Tavuklu Sultan Kebabı",
    "Beşamelli Tavuk",
    "Dalyan Köfte",
    "Kuzu İncik",
    "Et Graten",
    "Hünkar Beğendi",
    "Etli Türlü",
    "Çoban Kavurma",
    "Kaşarlı Fırın Köfte",
    "Beşamel Soslu Piliç Graten",
    "Kadınbudu Köfte",
    "Sebzeli Dizme Köfte",
    "Yoğurtlu Pideli Kebap",
    "Ekşili Sulu Köfte",
    "İslim Kebabı (Kuşbaşı Etli)",
    "Mini Burger",
    "Biberiyeli Biftek Izgara",
    "Çoban Kavurma",
    "Bitlis Usulü Ispanaklı Köfte",
    "Ispanaklı Tavuk Dolması",
    "Tandır",
    "Susamlı Krakerli Tavuk Parçaları",
    "Hindi Dolması",
    "Beşamel Soslu Ispanaklı Tavuk",
    "Sebzeli Tavuk",
    "Sini Kebabı",
    "Keşkek",
    "Fırında Cipsli Tavuk",
    "Juliet (Ananaslı Piliç Bonfile)",
    "Ev Yapımı Hamburger",
    "Dana Fümeli Omlet",
    "Terbiyeli Kuzu Şiş Ve Meyhane Pilavı",
    "Kuzu Tandır Ve Ispanak Püresi",
    "Tavuklu Patlıcan Oturtma",
    "Akhisar Köftesi",
    "Kuru Köfte",
    "Hünkar Beğendi",
    "Ali Nazik",
    "Terbiyeli Kuzu Haşlama",
    "Hürrem Sultan ",
    "Harem Güveci",
    "Hasanpaşa Köftesi"
]


export const vegetableFoods = [
    "Bal Kabağı Mücver Fırında",
    "Pancar Sapı Kavurması",
    "Havuç Mücver",
    "Domates Soslu Kızartma",
    "Patlıcan Kebabı",
    "Patatesli Yaz Fasulyesi",
    "Kabak Çiçeği Dolması",
    "Kuru Fasülye",
    "Karnıyarık",
    "İmam Bayıldı",
    "Fırında Pazı Mücver",
    "Pirinçli Pazı",
    "Mantar Sote",
    "Zeytinyağlı Bamya",
    "Sebze Sote",
    "Sebzeli Mücver Fırında",
    "Etli Terbiyeli Kereviz",
    "Börülce",
    "Tereyağlı Kabak",
    "Zeytinyağlı Ispanak",
    "Etli Nohutlu Bamya",
    "Zeytinyağlı Bakla",
    "Tavuklu Ve Mantarlı Karnıyarık",
    "Kereviz Oturtma",
    "Ispanaklı Kanape",
    "Mantar Güveç",
    "Kremalı Patates",
    "Fırında Pratik Türlü",
    "Zeytinyağlı Taze Fasulye",
    "Altın Renkli Arpacık Soğan",
    "Patates Graten",
    "Yaz Türlüsü",
    "Fırında Peynirli Patates",
    "Ispanaklı Yumurta",
    "Sandal Sefası",
    "Köfteli Enginar",
    "Fırında Ispanak",
    "Tavuklu Patlıcan Sarma",
    "Etli Kabak Yahni",
    "Zeytinyağlı Közlenmiş Patlıcanlı İmambayıldı",
    "Kabak Graten",
    "Etli Nohutlu Patlıcan",
    "Fırında Kabak Karnıyarık",
    "Pirinçli Kabak",
    "Kabak Kavurma",
    "İç Baklalı Enginar",
    "Pazı Kavurması",
    "Patlıcan Karnıyarık (Fırında)",
    "Pastırmalı Kuşkonmaz",
    "Kuşkonmazlı Tart",
    "Fırında Peynirli Kuşkonmaz",
    "Fırınlanmış Ispanaklı Mantar",
    "Patlıcan Musakka",
    "Karnıyarık",
    "Barbunya ",
    "Fasulye Kavurması ",
    "Hellim Peynirli Patlıcan",
    "Bulgur Topları",
    "Bezelyeli Enginar",
    "Zeytinyağlı Enginar ",
    "Barbunya Pilaki ",
    "Enginar Dolması ",
    "Zeytinyağlı Semizotu ",
    "Kabak Sefası",
    "Kıymalı Semizotu",
    "Zeytinyağlı Bamya ",
    "Nohutlu Pırasa ",
    "Pırasa Çullama ",
    "Portakal Yuvasında Avokadolu Enginar Kalbi",
    "Zeytinyağlı Bezelye",
    "Kabak Kalye ",
    "Kabak Kıytırık ",
    "Kabak Bayıldı",
    "İç Baklalı Zeytinyağlı Enginar",
    "Patlıcan Sarma",
    "Zeytinyağlı Sıcak Fasulye",
    "Yaz Türlüsü",
    "Yoğurtlu Pazı Sarması",
    "Ayvalı Kereviz",
    "Bulgurlu Kapuska",
    "Lahana Bohçası",
    "Portakallı Pırasa",
    "Kabaklama",
    "Zeytinyağlı Yerelması",
    "Zeytinyağlı Bakla",
    "Zeytinyağlı Ayva",
    "Zeytinyağlı Mantar",
    "Çam Fıstıklı Pazı Kavurması",
    "Zeytinyağlı Pırasa",
    "Beşamel Soslu Ispanak Graten",
    "Ekşili Patlıcan",
    "Zeytinyağlı Enginar",
    "Kıymalı Enginar Dolması",
    "Patlıcan Oturtma",
    "Ispanak Püresi",
    "Etli Bezelye",
    "Yoğurtlu Enginar Kızartması",
    "Zeytinyağlı Patlıcan Ruloları",
    "Zeytinyağlı Patlıcanlı Börülce",
    "Yumurtalı Taze Fasulye"
]



export const desserts = [
    "Vişneli Kek",
    "Çikolatalı Sufle",
    "Çikolatalı Fransız Keki",
    "Çikolatalı Bayat Ekmek Keki",
    "Çikolata Soslu Kek",
    "Mermer Kek",
    "Kadayıflı Muhallebi",
    "Browni Cheesecake ",
    "Elmalı Kek",
    "Kedidili Tiramisu",
    "Üç Malzemeli Mozaik Pasta",
    "Külahta Kek",
    "Tahinli Beyaz Çikolatalı Sufle",
    "Karpuzkek",
    "Çikolatalı Mini Pasta",
    "Nescafeli Yaş Pasta",
    "Meyveli Beze",
    "Çikolatalı Armut Tatlısı",
    "Kızarmış Çilek",
    "Narlı Çikolatalı Pancake",
    "Arpa Şehriyeli Sütlaç",
    "Portakal Soslu Kolay Krem Karamel",
    "Kaymaçina",
    "Şeftalili Ekmek Tatlısı",
    "Panna Cotta",
    "Portakallı Çikolatalı Pasta",
    "Limonlu Toplar",
    "Bisküvi Ve Çikolata Soslu Kup",
    "Kahveli Çikolatalı Mus",
    "Üzümlü Pelte",
    "Cezerye",
    "Meyveli Mini Tatlı Havuzu",
    "Karamelli Muz",
    "Havuçlu Parmak Tatlısı",
    "Dilek Tatlısı",
    "Samsa Tatlısı Kestaneli",
    "Kıtır Rüyası",
    "Soğuk Şerbetli İrmik Tatlısı",
    "Cookie Browni",
    "Sütlü Nuriye",
    "Fındıklı Tarçınlı Sütlaç",
    "Çilekli Dondurma",
    "Elma Reçeli",
    "Ekmek Kadayıfı (Yalancı)",
    "Donut",
    "Diyet Keşkül",
    "Çilekli Diyet Dondurma",
    "Çikolatalı Un Helvası",
    "Çikolatalı Sufle ",
    "Çikolatalı Puding",
    "Çikolatalı Muhallebi",
    "Çikolatalı Kup",
    "Çikolata Soslu İrmik Helvası",
    "Cevizli Tel Kadayıf",
    "Cevizli Baklava",
    "Bisküvili Pasta",
    "Ev Yapımı Cezerye",
    "Dankekli Kolay Pasta",
    "Brownie Cheesecake",
    "Lor (İrimşik) Böreği",
    "Cevizli Browni",
    "Fırında Şeftali",
    "Tahinli Dondurma",
    "Bougatsa Tatlısı",
    "Soğuk Föndü",
    "Nutellalı Kek",
    "Vişneli İrmik Tatlısı",
    "Vişneli Cheesecake",
    "Vişne Sosu",
    "Vişneli Fincan Tatlısı",
    "Çilek Sosu",
    "Çilekli Cheesecake",
    "Bisküvi Çanağında Çilek Sos Eşliğinde Çilek",
    "Kakaolu İncirli Kek",
    "Çikolata Soslu Kolay Pasta",
    "Kızarmış Dondurma",
    "Elmalı İrmik Tatlısı",
    "Fıstıklı Leblebi Helvası",
    "Susam Şekeri",
    "Pekmezli Un Helvası",
    "Alman Pastası",
    "Portakal Sulu İrmikli Kek",
    "Bisküvili Kabak Tatlısı",
    "Sahlepli Muhallebi",
    "Sufle",
    "Bisküvili Pasta",
    "Cevizli Üzümlü Kek",
    "Havuçlu Kek",
    "Damla Çikolatalı Muffin",
    "Üzümlü Kurabiye ",
    "Limonlu Şam Kurabiyesi",
    "Gebole Tatlısı",
    "Ay Çöreği",
    "Elmalı Kurabiye",
    "Kavala Kurabiyesi",
    "Muhallebili Muska Tatlısı",
    "Etimek Tatlısı",
    "Muhallebili Çıtır Kadayıf Rulosu",
    "Triliçe"
]


export const traditionals = [
    "İçli Köfte",
    "Aşure ",
    "Nokul",
    "Fellah Köftesi Hatay Usülü",
    "Patlıcan Böreği",
    "Havidz",
    "Akşehir Yahnisi",
    "Yoğurtlu Et",
    "Girit Kaymak Helvası (Staka)",
    "Ceviz Ezmesi",
    "Çiğ Köfte Hatay Usulü",
    "İçli Köfte (Oruk) Hatay Usulü",
    "Şiveydiz",
    "Sıyırga",
    "Soğanlama",
    "Sülbiye",
    "Abugannuş",
    "Haşhaşlı Amasya Çöreği",
    "Dible",
    "Beliş",
    "Arışıla",
    "Şıgıl Muhşi",
    "Aydın Çemeni",
    "Arapsaçı Kavurması",
    "Kırlı Patlıcan Kızartma",
    "Tosmankara  - Isparta",
    "Has Dolması (Bitlis Yemeği)",
    "Rize Kavurma",
    "Harput Köftesi",
    "Abdigor Köftesi",
    "Islama Köfte - Adapazarı Usulü",
    "Odun Köftesi - Manisa Usulü",
    "Yuvalaça  ",
    "Meftune  - Diyarbakır Usulü",
    "İzmir Köfte",
    "Simit Kebabı - Güneydoğu Anadolu Bölgesi",
    "Duvaklı Pilav (Diyarbakır)",
    "Zıngıl Tatlısı"
]

export const rises = [
    "Nohutlu Bulgur Pilavı",
    "Tavuklu Perde Pilavı",
    "Kabune",
    "Buhara Özbek Pilavı",
    "İç Pilav",
    "Bulgur Pilavı ( Mardin Usülü)",
    "Etli Nohutlu Pilav",
    "Tereyağlı Pirinç Pilavı",
    "Erzurum Usulü Patlıcanlı Pilav",
    "Turuncu Pilav",
    "Balkabaklı Pilav",
    "Çin Pilavı",
    "Perde Pilavı",
    "Patlıcanlı Pilav",
    "Biberli Pilav",
    "Fıstıklı Ve Üzümlü Pilav",
    "Haseki Pilavı",
    "Meyhane Pilavı",
    "Özbek Pilavı",
    "Dereotlu Ve Bademli Pilav",
    "Mantarlı Pilav",
    "Mercimekli Bulgur Pilavı",
    "Nohutlu Pilav",
    "Sebzeli Bulgur Pilavı",
    "Arpa Şehriyeli Pilav",
    "Sebzeli Pilav",
    "Şenlik Pilav",
    "Havuçlu Pilav",
    "İç Pilav ",
    "Taze Fasulyeli Bulgur Pilavı",
    "Patlıcanlı Pilav",
    "Soğanlı Bademli Mısırlı Pilav",
    "Antep Fıstıklı Pilav",
    "Havuçlu Ve Nohutlu Pilav",
    "Mengen Pilavı",
    "Safranlı Pilav",
    "Tavuklu Mantarlı Bulgur Pilavı",
    "Firik Pilavı",
    "Ali Paşa Pilavı",
    "Domatesli Pirinç Pilavı",
    "Arpa Şehriyeli Pilav",
    "İzmir Pilavı",
    "Enginarlı Pilav",
    "Tavuklu Nohutlu Pilav",
    "Şehriyeli Mercimekli Bulgur Pilavı",
    "Özbek Pilavı",
    "Tavuklu Kapama",
    "Perde Pilavı ",
    "Kestaneli Pilav",
    "Keşkek",
    "Buhara Pilavı",
    "Etli Dövme Pilavı",
    "Etli Firik Pilavı",
    "Çakır Pilav",
    "Ege Pilavı (Enginarlı Otlu Pilav)",
    "Bulgur Pilavı",
    "Balkabaklı Pilav",
    "Ekşili Pilav",
    "Alaca Pilav",
    "Etli Pirinç Pilavı",
    "Arpa Şehriye Pilavı",
    "Ciğerli İç Pilav",
    "Alipaşa Pilavı",
    "Midye Salma (Midyeli Pilav)",
    "Üzlemeli Pilav",
    "Tavuklu Nohutlu Pilav (Nohut Pilav)",
    "Meyhane Pilavı",
    "Mengen Pilavı",
    "Saray Pilavı",
    "Tel Şehriyeli Bulgur Pilavı",
    "Sebzeli Pilav",
    "Püsküllü (Civilli) Pilav",
    "Portakallı Bademli Pilav",
    "Patlıcanlı Bulgur Pilavı",
    "Havuçlu Bezelyeli Pilav"
]


export const macaronis = [
    "Kremalı Mantar Soslu Makarna Ravioli",
    "Linguine Makarna  Domates Soslu",
    "Yoğurtlu Kıymalı Makarna",
    "Fettucini Alfredo Soslu Makarna",
    "Soya Soslu Tavuklu Mantarlı Makarna",
    "Mantarlı Kremalı Makarna",
    "Kabaklı Peynirli Makarna",
    "Peynirli Ev Makarnası",
    "Domates Soslu Makarna ",
    "Domates Soslu Spagetti",
    "Cevizli Peynirli Erişte",
    "Kuşkonmazlı Makarna",
    "Mercimekli Şehriye Pilavı",
    "Bolonez Soslu Makarna",
    "Karidesli Makarna",
    "Köfteli Spagetti",
    "Deniz Mahsullü Spagetti",
    "İtalyan Usulu Bolonez Soslu Spagetti",
    "Mantarlı Tavuklu Spagetti",
    "Fırında Makarna",
    "Domatesli Kremalı Fırında Makarna",
    "Meksika Fasulyeli Ve Tavuklu Noodle",
    "Cevizli Kuskus",
    "Fırında Makarna",
    "Spaetzle",
    "Makarna Böreği",
    "Zeytinli Spagetti Makarna",
    "Kuru Domatesli Kuskus",
    "Makarna Böreği",
    "Sebzeli Arpa Şehriye Pilavı",
    "Fasulyeli Etli Makarna",
    "Fesleğen Soslu Üç Renkli Tartoloni",
    "Sebzeli Noodle",
    "Akdeniz Soslu Makarna",
    "Ispanaklı Ve Pastırmalı Fırın Makarna",
    "Çerkez Peynirli Ve Sebzeli Makarna",
    "Domates Makarna Graten",
    "Lazanya",
    "Nohutlu Kuskus Pilavı",
    "Tatlı Ekşi Soslu Sebzeli Noodle",
    "Domates Soslu Ispanaklı Ravioli",
    "Soğan Ve Salça Soslu Makarna",
    "Cevizli Keşli Erişte",
    "Pancarlı Kuskus",
    "Tavuklu Ravioli"
]

export const salads = [
    "Patates Kasesi",
    "Mercimek Köftesi",
    "Yeşilelmalı Havuç Salatası",
    "Tavuklu Makarna",
    "Taze Bakla Salatası",
    "Yeşil Mercimek Salatası",
    "Zahter Salatası",
    "Yoğurtlu Patlıcan",
    "Yoğurtlu Semizotu Salatası",
    "Yeşil Salata",
    "Yoğurtlu Taze Fasulye Salatası",
    "Tavuklu Sezar Salata",
    "Tatlandırıcılı Meyve Salatası",
    "Soğanlı Semizotu Salatası",
    "Sezar Salata",
    "Semizotu Salatası ",
    "Sardalya Salatası",
    "Salata",
    "Pırasa Salatası",
    "Patlıcan Salatası",
    "Pancarlı Lahana  Salatası",
    "Nohutlu Patlıcan Salatası",
    "Nohutlu Kinoa Salatası",
    "Mevsim Salata",
    "Marul Salatası",
    "Mantar Salatası",
    "Mamzana Salatası",
    "Lor Peynirli Salata",
    "Kıvırcık Salata",
    "Kırmızı Lahana Salatası",
    "Kinoa Salatası",
    "Kereviz Salatası",
    "Karides Salatası",
    "Karabuğday Salatası",
    "Kremalı Meyve Salatası",
    "Havuçlu Coleslaw Salatası",
    "Havuçlu Patates Salatası",
    "Havuç Salatası",
    "Hardal Soslu Kereviz Salatası",
    "Göbek Salata",
    "Gavurdağı Salatası",
    "Enginarlı Marul Salatası",
    "Enginar Salatası",
    "Ege Salatası",
    "Dondurmalı Meyve Salatası",
    "Domatesli Patlıcan Salatası",
    "Domates Salatası",
    "Deniz Börülcesi Salatası",
    "Çoban Salata",
    "Çiftlik Salatası",
    "Buğdaylı Mercimekli Salata",
    "Beyaz Peynirli Çoban Salata",
    "Sarımsaklı Börülce Salatası",
    "Domates Salatası",
    "Göbek Marul Salatası",
    "Kavunda Dondurmalı Meyve Salatası",
    "Yeşil Mercimek Salatası",
    "Kısır",
    "Taze Fasulye Salatası",
    "Patates Kayığında Kaşarlı Garnitür",
    "Kereviz Salatası",
    "Yeşil Elmalı Salata",
    "Karnabahar Salatası",
    "Beyaz Peynirli Köz Patlıcan Salatası",
    "Narlı Bulgur Salatası",
    "Brokoli Salatası",
    "Yumurta Salatası",
    "Dolmalık Biber Turşusu",
    "Hibeşli Karnabahar",
    "Maş Fasulyesi Salatası",
    "Ispanak Salatası",
    "Közlenmiş Biber Salatası",
    "Mısır Salatası",
    "Sumaklı Soğan Salatası",
    "Taze Fasulye Salatası",
    "Patates Salatası",
    "Kaşık Salata",
    "Roka Salatası",
    "Soslu Kırmızı Lahana Salatası",
    "Şef Mustafa'nın Salatası",
    "Grek Salata",
    "Domates Soslu Taze Börülce Salatası",
    "Çoban Salatası",
    "Makarna Salatası",
    "Portakallı Lahana Salatası",
    "Ispanaklı Falafelli Salata",
    "Radika Salatası Tarator Soslu",
    "Şevket-i Bostan  Salatası",
    "Turp Otu Salatası",
    "Semizotu Salatası",
    "Mor Lahana Turşusu",
    "Nar Taneli Buğday Salatası",
    "Kuru Börülce Salatası",
    "Pancarlı Kısır",
    "Kuşkonmaz Salatası",
    "Sebzeli Patlıcan Salatası ",
    "Tabule ",
    "Tarhun Soslu Salata",
    "Kalamar Salatası "
]

export const pastries = [
    "Çikolatalı Naneli Kek",
    "Kıymalı Kömbe",
    "Beyaz Peynirli Sucuklu Milföy Börek",
    "Peynirli Gül Böreği",
    "Ispanaklı Gül Börek",
    "Patatesli Midye Börek",
    "Bademli Çikolatalı Kek",
    "Meyveli Tartolet",
    "Peynirli Poğaça",
    "Tavuklu Cevizli Börek",
    "Çikolatalı Ay Çöreği",
    "Beyaz Çikolatalı Panettone",
    "Çikolatalı Ekmek",
    "Tatlı Yılbaşı Ekmeği",
    "Çikolata Kremalı Pişi",
    "Ballı Kek",
    "Baharatlı Kek",
    "Mandalinalı Kek",
    "Milföylü Kabaklı Pay",
    "Patatesli Tart",
    "Elmalı Bisküvi Pastası",
    "Yulaflı Kepek Ekmeği",
    "Patatesli Ekmek",
    "Baltacı Ekmeği",
    "Haşhaşlı Cevizli Simit",
    "Mahlepli Çörek",
    "Danimarka Çöreği",
    "Midye Poğaça",
    "Sarıklı Çörek",
    "Zeytinli Rulo",
    "Töpelek",
    "Fındıklı Çörek",
    "Milföylü Tombik",
    "Patates Hamuru İle Çörek",
    "Tuzlu Milföy",
    "Haşhaş Ezmeli Çörek",
    "Tarçınlı Açık Poğaça",
    "Cevizli Çörek",
    "Muffin Pizzalar",
    "Kır Pidesi ",
    "Kolay Pizza",
    "Enginarlı Pide",
    "Patlıcanlı Pizza",
    "Yufka Pizzası",
    "Hamsili Muska Böreği",
    "Fincan Böreği",
    "Sebzeli Kış Böreği",
    "Sodalı Börek",
    "Peynirli Börek",
    "Soğan Böreği",
    "Patlıcanlı Gül Börek",
    "Abaza Böreği",
    "Sebzeli Krep",
    "Çoban Böreği",
    "Beşamel Soslu Mantarlı Börek",
    "Lokum Börek",
    "Sebzeli Börek",
    "Mini Pizzalar",
    "Peynirli Sucuklu Milföy Börek",
    "Biftekli Milföy Börek",
    "Simit Börek",
    "Patlıcan Salatalı Börek",
    "Renkli Börek",
    "Sütlü Börek",
    "Kabak Mücver",
    "Ekmek Hamurlu Börek",
    "Pastırmalı Patatesli Börek",
    "Kol Böreği  (Hazır Yufkadan)",
    "Peynirli Çıtır Börek",
    "Domatesli Börek (Kolay Arnavut Böreği)",
    "Çaylı Kek",
    "Arnavut Böreği",
    "Taze Soğanlı Börek",
    "Nohutlu Muska Börek",
    "Sulu Börek",
    "Zarf Börek",
    "Midye Börek",
    "Sebzeli Çörek",
    "Sade Poğaça",
    "Poğaça ",
    "Peynirli Rulo Hamur",
    "Peynirli Pide",
    "Peynirli Börek",
    "Pazılı Rulo Börek",
    "Patlıcanlı Ravioli",
    "Patatesli Poğaça",
    "Patatesli Pide",
    "Patatesli Halkalar",
    "Patatesli Gözleme",
    "Mıhlama",
    "Lor Peynirli Gözleme",
    "Kuşbaşılı Pide",
    "Krep",
    "Kol Böreği",
    "Kıymalı Kaşarlı Pide",
    "Kır Pidesi",
    "Kepekli Simit",
    "Gözleme",
    "Fındıklı Tarçınlı Kurabiye",
    "Ev Yapımı Lahmacun"
]

export const snacks = [
    "Ispanaklı Tel Kadayıf",
    "Havuç Köftesi",
    "Mercimek Köftesi ",
    "Baharatlı Cips Ev Yapımı",
    "Makarna Cips",
    "Fesleğenli Patates Püresi",
    "Baharatlı Bebek Patates",
    "Tavada Bebek Patates",
    "Fırında Patlıcan Pizzası",
    "Cevizli Volavan",
    "Sucuklu Yumurta",
    "Patates Kavurma Yumurtalı",
    "Patlıcan Pizzası",
    "Kabak Cipsi",
    "Bayat Ekmek Köftesi",
    "Patlıcan Kıstırma",
    "Sarımsaklı Ekmek",
    "Omaç",
    "Lalezar",
    "Ev Yapımı Yoğurt",
    "Sarımsaklı Patates",
    "Mercimekli Köfte",
    "Lahana Ve Patatesli Mücver",
    "Salatalık Kanape",
    "Bal Kabağı  Mücveri",
    "Mantar Graten Kanepe",
    "Mantar Pane",
    "Çılbır",
    "Akıtma",
    "Patates Tart",
    "Kolay Soğuk Sandviç ",
    "Soğanlı Yumurta",
    "Baharatlı Patates Kroket",
    "Bruschetta",
    "Çıtır Tavuk Ve Ballı Hardallı Sos",
    "Mercimek Köftesi",
    "Renkli Patates Topları",
    "Çıtır Soğan Halkası",
    "Çıtır Kuşkonmazlar",
    "Havuç Cipsi ",
    "Domates Soslu Patates Kızartması",
    "İçli Köfte",
    "Domates Ve Salatalık Dolması"
]

export const drinks = [
    "Çilekli Milkshake",
    "Reyhan Şerbeti",
    "Naneli Ayran",
    "Yağlı Cacık",
    "Vişne Kompostosu ",
    "Vişne Hoşafı",
    "Türk Kahvesi (Şekerli)",
    "Türk Kahvesi (Sade)",
    "Taze Erik Kompostosu",
    "Sütlü Kahve (Şekerli)",
    "Sütlü Kahve",
    "Rezene Çayı",
    "Meyveli Soğuk Çay",
    "Diyet Limonata ",
    "Kuru Üzüm Hoşafı",
    "Kuru Kayısı Hoşafı",
    "Kuru Erik Hoşafı",
    "Kayısı Kompostosu",
    "Elma Kompostosu",
    "Sütlü Çay",
    "Çay (Tam Yağlı Süt İle)",
    "Ayran",
    "Karpuzlu Limonata ",
    "Dondurmalı Meyve Suyu",
    "Meyveli Süt",
    "Buzlu Mocha ",
    "Frappe",
    "Karpuz Limonatası",
    "Karpuzlu Limonata",
    "Elma Şerbeti",
    "Sarımsak Çayı",
    "Ev Yapımı Kolay Limonata ",
    "Tarçın Çayı",
    "Osmanlı Şerbeti",
    "French Press İle Filtre Kahve",
    "Ev Yapımı Limonata ",
    "Naneli Soğuk Yeşil Çay",
    "Maden Sulu Vişneli İçecek",
    "Kivili Kavunlu İçecek",
    "Üzüm Hoşafı",
    "Ahırkapı Şerbeti",
    "Çilek Kompostosu",
    "Vişne Şurubu",
    "Vişneli Smoothie"
]

export const breakfasts = [
    "Çocuk Omleti",
    "Kuru Domatesli Yumurta",
    "Ispanak Ve Peynirli Krep Pane",
    "Sütlü Peynirli Ekmek",
    "Kaşık Dökmesi",
    "Ev Yapımı Peynir",
    "Lor Peyniri ",
    "Domatesli Krep Sarma",
    "Çörekotlu Yumurtalı Ekmekler",
    "Kızarmış Peynir Topları",
    "Tortilla  (İspanyol Omleti)",
    "Peynirli Domates Fırında",
    "Biberli Peynir Kavurma",
    "Vişne Reçeli",
    "Yumurtalı Ekmek",
    "Yumurtalı Börülce",
    "Yulaflı Omlet",
    "Sucuklu Yumurta ",
    "Soğanlı Omlet",
    "Sahanda Yumurta",
    "Patatesli Omlet",
    "Omlet",
    "Menemen ",
    "Maydanozlu Omlet",
    "Mantarlı Omlet",
    "Lor Peynirli Omlet",
    "Ispanaklı Omlet",
    "Chia Tohumlu Omlet",
    "Beyaz Peynirli Yumurta",
    "Patates Yatağında Fırınlanmış  Yumurta",
    "Kürdan Böreği",
    "Muçari",
    "Sosisli Çöp Şiş",
    "Evde Çokokrem",
    "Kayısı Reçeli",
    "Sahanda Geyik",
    "Peynir Pane",
    "Menemen",
    "Sahanda Yumurta",
    "Çingen Pilavı",
    "Ekmekli Kolay Pizza",
    "Simit İçinde Yumurtalı Sucuk",
    "Yumurtalı Peynirli Ekmekler",
    "Kahvaltılık Krep",
    "Kuşkonmazlı Omlet",
    "Pankek ",
    "Nar Reçeli ",
    "Soğan Halkasında Yumurta",
    "Patatesli Omlet",
    "Ayva Reçeli",
    "Çilek Reçeli",
    "Limon Çiçeği Reçeli",
    "Muhallebili French Tost"
]

export const appetizers =[
    "Közlenmiş Yeşil Biber Salatası",
    "Panelenmiş Kabak",
    "Lutenitsa (Ajvar) Sos ",
    "Kırmızı Pulbiberli Yoğurt",
    "Tahinli Patlıcan Salatası",
    "Yoğurtlu Patlıcan Salatası",
    "Domates Soslu Karışık Kızartma",
    "Şakşuka",
    "Zeytinyağlı Enginar",
    "Yoğurtlu Havuç",
    "Sebzeli Meze",
    "Patlıcan Ezme",
    "Közlenmiş Patlıcan",
    "Hellim Peynirli Patlıcan Dilimleri",
    "Çiğ Köfte (Etsiz)",
    "Yoğurtlu Semizotu Salatası Biber Yatağında",
    "Girit Ezme",
    "Zeytinyağlı Havuç",
    "Yalancı Suşi",
    "Bamya Kızartması",
    "Taze Fasulye Kızartması",
    "Yoğurtlu Buğday Salatası",
    "Karnabahar Pane",
    "Tatlı Kırmızı Lahana",
    "Zeytin Piyazı",
    "Patates Mücveri",
    "Barbunya Pilaki",
    "Domates Soslu Patlıcan",
    "Fasulye Yoğurtlaması",
    "Taze Börülce Salatası",
    "Sebzeli Patates Püresi",
    "Mısırlı Mücver",
    "Kırmızı Biber Sarması",
    "Pirinç Köftesi",
    "Kaplanmış Kabak",
    "Sebzeli Mantar Sote",
    "Fırında Kaşarlı Mantar",
    "Karışık Kızartma",
    "Rum Böreği",
    "Yoğurtlu Kabak Kavurma",
    "Acılı Ezme",
    "Acılı Fasulye Ezmesi",
    "Çerkez Tavuğu",
    "Yoğurtlu Pancar Salatası",
    "Atom",
    "Cacık",
    "Fava",
    "Yoğurtlu Havuç Salatası",
    "Arnavut Ciğeri",
    "Köpoğlu Salatası",
    "Kabak Mücveri",
    "Sarımsaklı Kırmızı Biber Mezesi",
    "Muhammara ",
    "Sarımsaklı Mayonez "
]

export const diets = [
    "Fırında Kabak Kızartması",
    "Fırında Biber Kızartması",
    "Diyet Pirinç Salatası",
    "Brokoli Çorbası",
    "Diyet Patates Çorbası",
    "Tavuk Suyuna Çorba",
    "Bakla Çorbası",
    "Terbiyeli Taze Fasulye Çorbası",
    "Semizotu Çorbası",
    "Tok Tutan Karabuğday Çorbası",
    "Tortilla Pizza",
    "Meyveli Diyet Tiramisu ",
    "Diyet İskender ",
    "Hardal Soslu Bonfile",
    "Tavuk Salatası "
]

export const fishes =[
    "Karidesli Börek",
    "Balık Buğulama",
    "Hamsili Ekmek",
    "Kiremitte Levrek",
    "Asma Yaprağında Balık",
    "Badem Ve Fındık Kaplı Somon Mantar Sos Eşliğinde",
    "Somonlu Kuşkonmaz",
    "Hamsikoli - Hamsili Ekmek",
    "Hamsi Tava",
    "Hamsili Pilav",
    "Hamsili Pazılı Pilav"
]

export const cookies = [
    "Bademli Ayıcık Kurabiye",
    "Karpuz Kurabiye",
    "Çikolatalı Islak Kek",
    "Ballı Çikolatalı Kurabiye",
    "Çikolata Soslu Kurabiye",
    "Susamlı Zencefilli Kurabiye",
    "Çilek Kremalı Bisküvi",
    "Çikolatalı Bademli Kurabiye",
    "Sandviç Kurabiye",
    "Mısır Gevrekli Kopartma Kurabiye",
    "Çikolatalı Çatlak Kurabiye",
    "Elmalı Çikolatalı Kurabiye",
    "İncirli Top Kurabiye",
    "Buse Kurabiyesi",
    "Mısır Unlu Çikolatalı Kurabiye",
    "Mısır Gevrekli Kurabiye",
    "İngiliz Usulü Bisküvi (Kuki)",
    "Yulaflı Çikolatalı Kurabiye",
    "Elmalı Kurabiye ",
    "Çikolatalı Kurabiye",
    "Beyaz Çikolatalı  Cevizli Kurabiye",
    "Çay Kurabiyesi",
    "Tırtıl Kurabiye",
    "Çiçek Kurabiye",
    "Fıstıklı Kurabiye",
    "Kahveli Kurabiye",
    "Ballı Cevizli Kurabiye",
    "Üzümlü Islak Kurabiye",
    "Kreviç",
    "Marmelatlı Kurabiye",
    "Yüzük Kurabiye",
    "Karanfilli Ve Zencefilli Kurabiye",
    "Kayısılı Bisküvi",
    "Susamlı Tatlı Kurabiye",
    "Yulaflı Çıtır",
    "Hardallı Peynir Krakeri",
    "Acılı Kurabiye",
    "Corn Flakesli Kurabiye",
    "Üzümlü Kurabiye",
    "Diyet Tarçınlı Kurabiye",
    "Kolace  (Lor Peynir Ve Elmalı Kurabiye)",
    "Tuzlu Bisküvi",
    "Köpük Kurabiye",
    "Marmelatlı Bisküvi",
    "Susamlı Halka Kurabiye",
    "Lor Kurabiyesi",
    "Un Kurabiyesi",
    "5 Dakika Kurabiyesi",
    "Cocostar Kurabiye",
    "Kıtır Bisküviler",
    "Şeftali Şurubunda Kurabiye",
    "Tahıllı Kurabiye",
    "Kakaolu Ve Sade Un Kurabiyesi",
    "Elmalı Kurabiye",
    "Üzümlü Cevizli Kurabiye",
    "Tarçınlı Kurabiye",
    "Unsuz Kurabiye",
    "Sevgililer Günü Kurabiyesi",
    "İki Renkli Kurabiye",
    "Anneler Günü Kurabiyesi",
    "Bademli Kurabiye",
    "Bohça Kurabiye",
    "Islak Kurabiye",
    "Fıstık Ezmeli Kurabiye",
    "Vitray Kurabiye",
    "Lokumlu Antep Fıstıklı Kurabiye",
    "Yeni Yıl Kurabiyesi",
    "İki Renkli Çiçek (Papatya) Kurabiye",
    "Reçelli Kurabiye",
    "Çikolata Parçacıklı Kurabiye",
    "Tarçınlı Kurabiye",
    "Üzümlü Elmalı Kurabiye",
    "Arapbacı Kurabiyesi",
    "Bademli Kurabiye",
    "Damla Sakızlı Kurabiye",
    "Kakaolu Islak Kurabiye",
    "Damla Çikolatalı Kurabiye",
    "Kalp Kurabiye",
    "Reçelli Kurabiye",
    "Siyah Beyaz Çikolatalı Kurabiye",
    "Hindistan Cevizli Kurabiye",
    "Mozaik Kurabiye",
    "Vişneli Top Kurabiye",
    "Elmalı Islak Kurabiye",
    "Perişan Kurabiye"
]


export const dolmas = [
    "Zeytinyağlı Yaprak Sarma ",
    "Kabak Çiçeği Dolması ",
    "Patlıcanlı Domates Dolması",
    "Domates Dolması",
    "Lorlu Pazı Sarma",
    "Zeytinyağlı Yaprak Sarma",
    "Etli Yaprak Sarması",
    "Yaprak Sarma ",
    "Kuşbaşılı Kuru Patlıcan Dolması",
    "Salatalık Dolması",
    "Soğan Dolması",
    "Kuru Patlıcan Dolması",
    "Zeytinyağlı Sarma",
    "Zeytinyağlı Biber Dolması",
    "Yoğurtlu Kabak Dolması",
    "Karalahana Dolması",
    "Kabak Çiçeği Dolması ",
    "Bakla Dolması",
    "Zeytinyağlı Biber Dolması",
    "Zeytinyağlı Vişneli Yaprak Sarma",
    "Zeytinyağlı Beyaz Lahana Sarma",
    "Soğan Dolması",
    "Köz Patlıcanlı Domates Dolması",
    "Zeytinyağlı Kuru Dolma",
    "Bezelyeli Girit Kabağı Dolması",
    "Renkli Zeytinyağlı Biber Dolması"
]

export const legumes=[
    "Bulgur Böreği",
    "Zeytinyağlı Barbunya Pilaki",
    "Tahinli Yulaf Galetası",
    "Etsiz Nohut Yemeği",
    "Mercimekli Kısır",
    "Mercimek Yemeği",
    "Kuru Fasulye Piyazı",
    "Kuru Fasulye Ezmesi",
    "Etsiz Kuru Fasülye",
    "Etli Kuru Fasulye ",
    "Kıymalı Yeşil Mercimek",
    "Güveçte Pastırmalı Kuru Fasulye",
    "Domatesli Kuru Fasulye",
    "Falafel (Nohut Köftesi)",
    "Kuru Fasulye",
    "Zeytinyağlı Taze Fasulye ",
    "Etli Kuru Fasulye",
    "Erişteli Yeşil Mercimek",
    "Etli Barbunya",
    "Güveçte Sucuklu Kuru Fasulye",
    "Kuzu Etli Nohut"
]
